openapi: 3.0.0
info:
  title: Marketplace API - Clients (Buyers)
  version: 1.0.0
paths:
  /buyers:
    get:
      summary: Get all buyers
      # ... (existing buyers endpoint details)

    post:
      summary: Create a new buyer
      # ... (existing buyer creation details)

  /buyers/{buyerId}/cart:
    get:
      summary: Get the buyer's shopping cart
      # ... (existing shopping cart endpoint details)

    post:
      summary: Add a product to the buyer's shopping cart
      # ... (existing add product to cart details)

  /buyers/{buyerId}/checkout:
    post:
      summary: Initiate the checkout process
      # ... (existing checkout initiation details)

  /buyers/{buyerId}/orders:
    get:
      summary: Get all orders placed by a buyer
      # ... (existing orders endpoint details)
