openapi: 3.0.0
info:
  title: Marketplace API - Monitoring & Reporting
  version: 1.0.0
paths:
  /admin/companies:
    get:
      summary: Get a list of all companies
      # ... (existing admin companies endpoint details)

  /admin/users:
    get:
      summary: Get a list of all users
      # ... (existing admin users endpoint details)

  /admin/orders:
    get:
      summary: Get a list of all orders
      # ... (existing admin orders endpoint details)
